"""add cascades to tasks chat

Revision ID: 183c0eb6f3d3
Revises: ccab95415a10
Create Date: 2026-06-09 19:36:27.163938

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "183c0eb6f3d3"
down_revision: Union[str, Sequence[str], None] = "ccab95415a10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("chatsession_task_id_fkey"), "chatsession", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "chatsession", "task", ["task_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint(
        op.f("subtaskdependency_predecessor_id_fkey"),
        "subtaskdependency",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("subtaskdependency_successor_id_fkey"),
        "subtaskdependency",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "subtaskdependency",
        "subtask",
        ["predecessor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "subtaskdependency",
        "subtask",
        ["successor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subtaskdependency", type_="foreignkey")
    op.drop_constraint(None, "subtaskdependency", type_="foreignkey")
    op.create_foreign_key(
        op.f("subtaskdependency_successor_id_fkey"),
        "subtaskdependency",
        "subtask",
        ["successor_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("subtaskdependency_predecessor_id_fkey"),
        "subtaskdependency",
        "subtask",
        ["predecessor_id"],
        ["id"],
    )
    op.drop_constraint(None, "chatsession", type_="foreignkey")
    op.create_foreign_key(
        op.f("chatsession_task_id_fkey"), "chatsession", "task", ["task_id"], ["id"]
    )
    # ### end Alembic commands ###
