"""add user ownership to tasks and chat sessions

Revision ID: 44d5ffd4016a
Revises: d4f8a1c9b2e3
Create Date: 2026-06-18 21:30:08.558870

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "44d5ffd4016a"
down_revision: Union[str, Sequence[str], None] = "d4f8a1c9b2e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM chatmessage"))
    op.execute(sa.text("DELETE FROM chatsession"))
    op.execute(sa.text("DELETE FROM subtaskdependency"))
    op.execute(sa.text("DELETE FROM subtask"))
    op.execute(sa.text("DELETE FROM task"))

    op.add_column("chatsession", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_chatsession_user_id"), "chatsession", ["user_id"], unique=False)
    op.create_foreign_key("chatsession_user_id_fkey", "chatsession", "user", ["user_id"], ["id"])
    op.add_column("task", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_task_user_id"), "task", ["user_id"], unique=False)
    op.create_foreign_key("task_user_id_fkey", "task", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("task_user_id_fkey", "task", type_="foreignkey")
    op.drop_index(op.f("ix_task_user_id"), table_name="task")
    op.drop_column("task", "user_id")
    op.drop_constraint("chatsession_user_id_fkey", "chatsession", type_="foreignkey")
    op.drop_index(op.f("ix_chatsession_user_id"), table_name="chatsession")
    op.drop_column("chatsession", "user_id")
    # ### end Alembic commands ###
