"""fk_focus_sesh_task

Revision ID: 81acc2371abc
Revises: 781ff0499f7f
Create Date: 2026-06-29 11:55:35.497862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81acc2371abc'
down_revision: Union[str, Sequence[str], None] = '781ff0499f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('focussession', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('focussession_task_id_fkey'), 'focussession', type_='foreignkey')
    op.create_foreign_key(None, 'focussession', 'task', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'focussession', type_='foreignkey')
    op.create_foreign_key(op.f('focussession_task_id_fkey'), 'focussession', 'task', ['task_id'], ['id'])
    op.alter_column('focussession', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
