"""init

Revision ID: bee7d2df38c2
Revises:
Create Date: 2026-07-27 13:22:17.244817

"""
from typing import Sequence, Union

from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bee7d2df38c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('focussession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('abandon_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_op_id', sa.Uuid(), nullable=True),
    sa.Column('work_cycle_m', sa.Integer(), nullable=False),
    sa.Column('rest_cycle_m', sa.Integer(), nullable=False),
    sa.Column('work_cycles', sa.Integer(), nullable=False),
    sa.Column('rest_cycles', sa.Integer(), nullable=False),
    sa.Column('total_overtime_s', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_focussession_user_id'), 'focussession', ['user_id'], unique=False)
    op.create_table('friendship',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('accepted_at IS NULL OR accepted_at >= requested_at', name='ck_friendship_accept_order'),
    sa.CheckConstraint('requester_id <> recipient_id', name='ck_friendship_distinct_users'),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friendship_recipient_id'), 'friendship', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_friendship_requester_id'), 'friendship', ['requester_id'], unique=False)
    op.create_index('uq_friendship_user_pair', 'friendship', [sa.literal_column('LEAST(requester_id, recipient_id)'), sa.literal_column('GREATEST(requester_id, recipient_id)')], unique=True)
    op.create_table('oauth_account',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_name', 'account_id', name='uq_oauth_account_oauth_name_account_id')
    )
    op.create_index(op.f('ix_oauth_account_account_id'), 'oauth_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_account_oauth_name'), 'oauth_account', ['oauth_name'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_op_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_user_id'), 'task', ['user_id'], unique=False)
    op.create_table('chatsession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatsession_user_id'), 'chatsession', ['user_id'], unique=False)
    op.create_table('nudge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('friendship_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['friendship_id'], ['friendship.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nudge_friendship_id'), 'nudge', ['friendship_id'], unique=False)
    op.create_index(op.f('ix_nudge_sender_id'), 'nudge', ['sender_id'], unique=False)
    op.create_table('restlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('focus_session_id', sa.Uuid(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('stop_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['focus_session_id'], ['focussession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restlog_focus_session_id'), 'restlog', ['focus_session_id'], unique=False)
    op.create_table('subtask',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('est_m', sa.Integer(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('completed_at IS NULL OR is_done', name='ck_subtask_completed_when_done'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtask_completed_at'), 'subtask', ['completed_at'], unique=False)
    op.create_index(op.f('ix_subtask_title'), 'subtask', ['title'], unique=False)
    op.create_table('chatmessage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM', 'ASSISTANT', 'TOOL', 'USER', name='role'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tool_call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chatsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('focuslog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('focus_session_id', sa.Uuid(), nullable=False),
    sa.Column('subtask_id', sa.Uuid(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('stop_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['focus_session_id'], ['focussession.id'], ),
    sa.ForeignKeyConstraint(['subtask_id'], ['subtask.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_focuslog_focus_session_id'), 'focuslog', ['focus_session_id'], unique=False)
    op.create_index(op.f('ix_focuslog_subtask_id'), 'focuslog', ['subtask_id'], unique=False)
    op.create_table('subtaskdependency',
    sa.Column('predecessor_id', sa.Uuid(), nullable=False),
    sa.Column('successor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_id'], ['subtask.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['subtask.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('predecessor_id', 'successor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtaskdependency')
    op.drop_index(op.f('ix_focuslog_subtask_id'), table_name='focuslog')
    op.drop_index(op.f('ix_focuslog_focus_session_id'), table_name='focuslog')
    op.drop_table('focuslog')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_subtask_title'), table_name='subtask')
    op.drop_index(op.f('ix_subtask_completed_at'), table_name='subtask')
    op.drop_table('subtask')
    op.drop_index(op.f('ix_restlog_focus_session_id'), table_name='restlog')
    op.drop_table('restlog')
    op.drop_index(op.f('ix_nudge_sender_id'), table_name='nudge')
    op.drop_index(op.f('ix_nudge_friendship_id'), table_name='nudge')
    op.drop_table('nudge')
    op.drop_index(op.f('ix_chatsession_user_id'), table_name='chatsession')
    op.drop_table('chatsession')
    op.drop_index(op.f('ix_task_user_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_oauth_account_oauth_name'), table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'), table_name='oauth_account')
    op.drop_table('oauth_account')
    op.drop_index('uq_friendship_user_pair', table_name='friendship')
    op.drop_index(op.f('ix_friendship_requester_id'), table_name='friendship')
    op.drop_index(op.f('ix_friendship_recipient_id'), table_name='friendship')
    op.drop_table('friendship')
    op.drop_index(op.f('ix_focussession_user_id'), table_name='focussession')
    op.drop_table('focussession')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
