from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from src.models.chat import ChatMessage, ChatSession, Role
from src.models.focus_session import FocusSession
from src.models.task import Subtask, Task
from src.models.user import User
from src.schemas.analytics import AnalyticsSummary
from src.schemas.focus_session import RestLogData, WorkLogData
from src.schemas.task import CreateTask, UpdateTask


class UserRepoProtocol(Protocol):
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
    async def upsert(self, obj: User) -> User: ...


class TaskRepoProtocol(Protocol):
    async def read_map(self, task_id: UUID) -> Task: ...
    async def create_map(self, roadmap: CreateTask, user_id: UUID) -> Task: ...
    async def read_subtask(self, subtask_id: UUID) -> Subtask: ...
    async def read_maps(self, user_id: UUID, offset: int, limit: int) -> list[Task]: ...
    async def update_map(self, task_id: UUID, roadmap: UpdateTask) -> None: ...
    async def delete_soft(self, task_id: UUID) -> None: ...
    async def update_done_subtask(self, subtask_id: UUID) -> Subtask: ...
    async def update_done_subtasks(self, subtask_ids: list[UUID]) -> list[Subtask]: ...
    async def read(self, id: UUID) -> Task: ...


class ChatRepoProtocol(Protocol):
    async def get_history(
        self, session_id: UUID, limit: int = 20, page: int = 1
    ) -> Sequence[ChatMessage]: ...
    async def add_message(
        self,
        session_id: UUID,
        role: Role,
        content: str,
        tool_call_id: str | None = None,
    ) -> ChatMessage: ...


class SessionRepoProtocol(Protocol):
    async def read(self, session_id: UUID) -> ChatSession: ...
    async def upsert(self, obj: ChatSession) -> ChatSession: ...
    async def link_task_to_session(self, session_id: UUID, task_id: UUID) -> ChatSession: ...


class FocusSessionRepoProtocol(Protocol):
    async def read(self, session_id: UUID) -> FocusSession: ...
    async def upsert(self, obj: FocusSession) -> FocusSession: ...
    async def read_active(self, user_id: UUID) -> FocusSession | None: ...
    async def create_focus_logs(self, session_id: UUID, logs: list[WorkLogData]) -> None: ...
    async def create_rest_logs(self, session_id: UUID, logs: list[RestLogData]) -> None: ...


class AnalyticsRepoProtocol(Protocol):
    async def read_summary(self, user_id: UUID) -> AnalyticsSummary: ...
