AUTH_BACKEND_NAME = "cookie"
AUTH_COOKIE_PATH = "/"
AUTH_COOKIE_HTTPONLY = True
AUTH_COOKIE_SAMESITE = "lax"
DUMMY_PASSWORD_HASH = (
    "pbkdf2_sha256$600000$qQjrGw975m9RRP1wxLj0zg==$4bsYoHPbLfbQTMmCutWTWJGF4mIb4+zdsKcwWq0yw4s="
)
